services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    ports: 
      - 8080:80

  client:
    build: 
      context: .
      dockerfile: client.Dockerfile

  server:
    build: 
      context: .
      dockerfile: server.Dockerfile